// Auto-generated by sync_meals.applescript — do not edit manually
// To add meals, edit the "Meal Database" Apple Note
// Format: "Meal Name - liam" | "Meal Name - chi" | "Meal Name - both"
const MEALS = [
  { name: "Malaysian Satay Supreme", chef: "liam" },
  { name: "Chicken Salad Surprise", chef: "liam" },
  { name: "Lovely Quiche Lorraine", chef: "liam" },
  { name: "Beef Burger Bonanza", chef: "liam" },
  { name: "Thai Green Curry Galore", chef: "liam" },
  { name: "Asian Noodle Salad", chef: "chi" },
  { name: "Buddha Bowls", chef: "chi" },
  { name: "Falafel Wraps", chef: "chi" },
  { name: "Poke Bowls", chef: "chi" },
  { name: "Mexican Nut Mince", chef: "chi" },
  { name: "Paneer Curry", chef: "chi" },
  { name: "Peanut Stew", chef: "chi" },
  { name: "Fritters", chef: "chi" },
  { name: "Moroccan Tagine", chef: "chi" },
  { name: "Vege Burgers", chef: "chi" },
  { name: "Pasta Verde", chef: "chi" },
  { name: "Soup", chef: "chi" },
  { name: "Kung Pao Tofu", chef: "chi" },
];

if (typeof module !== "undefined") module.exports = MEALS;

