#!/usr/bin/env python3
"""
parse_note.py — Parses "Meal Database" Apple Note content into meals.js

Usage: python3 parse_note.py <note_txt_file> <output_meals_js>

Note format — one meal per line:
  Meal Name - liam
  Meal Name - chi
  Meal Name - both

Lines beginning with -- or // are treated as comments and ignored.
"""

import re
import sys

HEADER = """\
// Auto-generated by sync_meals.applescript — do not edit manually
// To add meals, edit the "Meal Database" Apple Note
// Format: "Meal Name - liam" | "Meal Name - chi" | "Meal Name - both"
const MEALS = [\
"""

FOOTER = """\
];

if (typeof module !== "undefined") module.exports = MEALS;
"""


def parse_meals(text):
    meals = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("--") or line.startswith("//"):
            continue
        m = re.match(r"^(.+?)\s*-\s*(liam|chi|both)\s*$", line, re.IGNORECASE)
        if m:
            name = m.group(1).strip()
            chef = m.group(2).strip().lower()
            meals.append((name, chef))
    return meals


def write_meals_js(meals, path):
    lines = [HEADER]
    for name, chef in meals:
        escaped = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  {{ name: "{escaped}", chef: "{chef}" }},')
    lines.append(FOOTER)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(meals)} meals to {path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <note_txt_file> <output_meals_js>")
        sys.exit(1)

    note_file, output_file = sys.argv[1], sys.argv[2]

    with open(note_file) as f:
        text = f.read()

    meals = parse_meals(text)

    if not meals:
        print("Warning: no meals parsed from note — meals.js not updated.")
        sys.exit(0)

    write_meals_js(meals, output_file)
